name: jordan Insights
description: Fetch jordan function insights
author: AuroraLabs
inputs:
  project:
    description: Name of the project to retrieve insights for
    required: true
  version:
    description: Version of the project to retrieve insights for
    required: true
  api-token:
    description: jordan API token for authentication
    required: true
  backend-url:
    description: jordan backend URL
    required: false
    default: "https://api.daily.loci-dev.net/"
runs:
  using: node20
  main: dist/index.js