name: jordan
description: Line of Code Insights Tool
inputs:
  mode:
    description: Mode to run
    required: true
  requirements-file:
    description: Path to requirements.txt
    required: false
    default: requirements.txt
  binaries:
    description: Paths to binaries to upload
    required: false
  project:
    description: Name of the existing project for which to retrieve function insights
    required: false
  version:
    description: Version of the project for which to retrieve function insights
    required: false
  api-token:
    description: jordan API token for authentication
    required: true
  backend-url:
    description: jordan backend URL
    required: false
    default: "https://api.daily.loci-dev.net/"
runs:
  using: node20
  main: dist/index.js
