name: Test jordan Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test Upload Mode
        uses: ./
        with:
          mode: upload
          project: test-project
          version: v1.0.0
          binaries: |
            README.md
            action.yml
          api-token: ${{ secrets.JORDAN_API_TOKEN }}
          
  test-insights:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test Insights Mode
        uses: ./
        with:
          mode: insights
          project: test-project
          version: v1.0.0
          api-token: ${{ secrets.JORDAN_API_TOKEN }} 